### ISSUE TITLE
Timing problems - better to use writeValueWithResponse

### ISSUE THREAD

**Issue by cimpok** [odensc/phomemo-d30-web-bluetooth#1]
First of all, thank you for the example code of how to print on a Phomemo Bluetooth printer. I managed to use it on the wider, and higher resolution model, the Phomemo M04AS.
One thing you or other users might find useful, is that after a lot of searching for the cause of a nasty error of randomly stopping printing, at last I found the problem:
in the printer.js module I changed  all    characteristic.writeValueWithoutResponse methods  to  characteristic.writeValueWithResponse,  and that solved the unreliable data transfer problem.
I guess, the writeValueWithoutResponse is better suited for streaming devices where an intermittent data loss is OK. With a printer it is not the case.

**Comment by odensc** [comment]
Thanks! I haven't run into any issues but it may be dependent on hardware/OS or due to the higher resolution of your printer. I've updated to using `writeValueWithResponse`.
