### ISSUE TITLE
Can't add a second line

### ISSUE THREAD

**Issue by AliBello** [odensc/phomemo-d30-web-bluetooth#2]
When trying to enter something to print, the text is too big, so I tried to enter a new line, but that didn't work.

Windows 11 Pro 23H2
Chrome 130.0.6723.117

Using the demo website (https://odensc.github.io/phomemo-d30-web-bluetooth/)

![image](https://github.com/user-attachments/assets/246e3a49-4998-47ad-b8f1-992f89875957)
Normal text

![image](https://github.com/user-attachments/assets/f7f4a307-b097-4309-8592-e60abb58e2ab)
Long text

![image](https://github.com/user-attachments/assets/95616861-1b31-4e5c-8b3e-0ecc530a3974)
No newline support

![image](https://github.com/user-attachments/assets/666b0684-544f-4439-86bf-15902aee887f)
When the input tag is switched with a textarea tag, it still does not work

**Comment by odensc** [comment]
Thanks for the feedback, I built this for a very simple use case that didn't need advanced text rendering. I've committed an update to support multiline text wrapping as well as changing the font size. Please give it a try :)
